### ISSUE TITLE
Country option is not working

### ISSUE THREAD

**Issue by seansco** [garrylachman/covid19-cli#1]
When i try the country option it just prints the Global Statistics:
----
 $ bash covid19-cli.sh --country USA
 ✔  Global Statistics
Cases: 252773, Deaths: 10405, Recovered: 89060

**Comment by garrylachman** [comment]
```
./covid19-cli.sh --country=USA 
 ✔  Country: USA
Cases: 14372, Deaths: 218, Recovered: 125
```

**Comment by seansco** [comment]
I'm running Ubuntu 18.04.4 LTS

$ bash covid19-cli.sh --country=USA
 ✔  Global Statistics
Cases: 254801, Deaths: 10447, Recovered: 89915

$ bash covid19-cli.sh -c=USA
invalid option: -U

$ ./covid19-cli.sh --country=USA
 ✔  Global Statistics
Cases: 254801, Deaths: 10447, Recovered: 89915

$ ./covid19-cli.sh -c=USA
invalid option: -U

i$ ./covid19-cli.sh -h
covid19-cli.sh [OPTION]...

 Corona Virus (Covid-19) statistics cli.

 MIT License
 Copyright (c) 2020 Garry Lachman
 https://github.com/garrylachman/covid19-cli

 Options:
  -c, --country     Specific Country
  -l, --list-all         List all countries
                    this through the interactive option
  -h, --help        Display this help and exit
      --version     Output version information and exit

i$ ./covid19-cli.sh --version
covid19-cli.sh v0.1

**Comment by JanBrezina** [comment]
@seansco pull, I believe it's fixed

**Comment by seansco** [comment]
if I run it with bash it's is working now but if I run it as an executable I get a script error.

$ ./covid19-cli.sh
./covid19-cli.sh: 16: ./covid19-cli.sh: [[: not found
./covid19-cli.sh: 19: ./covid19-cli.sh: Syntax error: "(" unexpected

$ bash covid19-cli.sh
 ✔  Global Statistics
Cases: 255733, Deaths: 10495, Recovered: 89918

$ bash covid19-cli.sh --country=USA
 ✔  Country: USA
Cases: 14373, Deaths: 218, Recovered: 125

**Comment by JanBrezina** [comment]
@seansco different problem, change 'sh' to 'bash' on the first line and maybe create another issue
