### ISSUE TITLE
Sorting does not work correctly

### ISSUE THREAD

**Issue by SemperEnim** [garrylachman/covid19-cli#11]
command covid19-cli.sh -l -s Active always sorts by Cases

![ipahKBJ](https://user-images.githubusercontent.com/62520140/77259084-68883b80-6c55-11ea-9dc3-2d207f4ced4a.png)

Also reproduced with Today-Cases

![image](https://user-images.githubusercontent.com/62520140/77259101-8fdf0880-6c55-11ea-8d21-821239c6ba6b.png)

**Comment by garrylachman** [comment]
```
  -s, --sort        Sort countries list by key (country|cases|active|critical|deaths|recovered|todayCases|todayDeaths|casesPerOneMillion)
```

Its a case-sensitive, please use one of `country, cases, active, critical, deaths, recovered, todayCases, todayDeaths, casesPerOneMillion`
