### ISSUE TITLE
Your build instructions seem to be missing a step

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [garrylachman/covid19-cli#14]
I believe the instructions should be as follows. I embolden the step you seem to be missing.

git clone https://github.com/garrylachman/covid19-cli.git
**cd covid19-cli**
make

**Comment by MyopicPaideia** [comment]
Getting the following output every now and then, definitely not every time, but about 1 in 5 maybe...

`parse error: Invalid numeric literal at line 1, column 7`

**Comment by LinuxOnTheDesktop** [comment]
@MyopicPaideia 

Me too, but that is a separate issue. Please file a separate report for it.

**Comment by garrylachman** [comment]
1. `git clone https://github.com/garrylachman/covid19-cli.git`
2. `cd cd covid19-cli`
3. `make`

README.md updated.
Thanks
