### ISSUE TITLE
Add punctuation to the numbers in the output

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [garrylachman/covid19-cli#16]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when interpreting the output is hard because the output lacks punctuation.

**Describe the solution you'd like**
Add punctuation to the output. Thus, `10000` should be `10,000` or - depending on the locale - `10.000`. I imagine that BASH should make it fairly easy to make the change.

**Describe alternatives you've considered**
I can think of no alternative remedy for the problem.

**Comment by garrylachman** [comment]
Adding punctuation, the only place i can't do it now is in countries list.
The columns are seperated by ,.

**Comment by LinuxOnTheDesktop** [comment]
Thanks. However - and unless I make some mistake in building the application - I see this:

`line 9: warning: setlocale: LC_NUMERIC: cannot change locale (en_US): No such file or directory`

Indeed: I am unsure that the program should be even _trying_ to set the locale to en_US. For, that is not my locale.
