### ISSUE TITLE
endpoints have been deprecated

### ISSUE THREAD

**Issue by Phalelashvili** [garrylachman/covid19-cli#18]
lmao.ninja v1 api endpoints have been deprecated. use v2

**Comment by lesnake** [comment]
Here is a patch

diff --git a/src/defines.sh b/src/defines.sh
index 9c3e8b2..b74f035 100644
--- a/src/defines.sh
+++ b/src/defines.sh
@@ -2,5 +2,5 @@ VERSION="0.2.4"
 
 BASE_API="https://corona.lmao.ninja"
 API_TOTAL_ENDPOINT="$BASE_API/all"
-API_ALL_COUNTRIES_ENDPOINT="$BASE_API/countries"
-API_HISTORICAL_COUNTRIES_ENDPOINT="$BASE_API/v2/historical"
\ No newline at end of file
+API_ALL_COUNTRIES_ENDPOINT="$BASE_API/v2/countries"
+API_HISTORICAL_COUNTRIES_ENDPOINT="$BASE_API/v2/historical"

**Comment by Phalelashvili** [comment]
> Here is a patch
> 
> diff --git a/src/defines.sh b/src/defines.sh
> index 9c3e8b2..b74f035 100644
> --- a/src/defines.sh
> +++ b/src/defines.sh
> @@ -2,5 +2,5 @@ VERSION="0.2.4"
> 
> BASE_API="https://corona.lmao.ninja"
> API_TOTAL_ENDPOINT="$BASE_API/all"
> -API_ALL_COUNTRIES_ENDPOINT="$BASE_API/countries"
> -API_HISTORICAL_COUNTRIES_ENDPOINT="$BASE_API/v2/historical"
> \ No newline at end of file
> +API_ALL_COUNTRIES_ENDPOINT="$BASE_API/v2/countries"
> +API_HISTORICAL_COUNTRIES_ENDPOINT="$BASE_API/v2/historical"

I've already patched it. just wanted to inform you.

EDIT: didn't realize it wasn't the author of repo who replied lol.
