### ISSUE TITLE
All stats are zero when searching for a country

### ISSUE THREAD

**Issue by QazCetelic** [garrylachman/covid19-cli#21]
**Describe the bug**
All stats are zero when searching for a country

**To Reproduce**
1.'./covid19-cli.sh -c Netherlands'
2. See error

**Expected behavior**
It probably should show other numbers than 0

**Screenshots**
./covid19-cli.sh -c Netherlands

**Desktop:**
 - OS: [KDE NEON]

**Software versions**
- Bash version: [4.4.20]

**Comment by Anindra123** [comment]
change the line on BASE_API on covid19-cli.sh from
BASE_API="https://corona.lmao.ninja"
to 
BASE_API="https://corona.lmao.ninja/v2"

this worked for me but there are still two error message showing also the graphical view is gone
