### ISSUE TITLE
Works with bash but not sh

### ISSUE THREAD

**Issue by seansco** [garrylachman/covid19-cli#5]
if I run it with bash it's is working now but if I run it as an executable I get a script error.
I'm on Ubuntu 18.04.4
changing first line to "#!/usr/bin/env bash" did fix the issue

$ ./covid19-cli.sh
./covid19-cli.sh: 16: ./covid19-cli.sh: [[: not found
./covid19-cli.sh: 19: ./covid19-cli.sh: Syntax error: "(" unexpected

$ bash covid19-cli.sh
✔ Global Statistics
Cases: 255733, Deaths: 10495, Recovered: 89918

$ bash covid19-cli.sh --country=USA
✔ Country: USA
Cases: 14373, Deaths: 218, Recovered: 125

**Comment by garrylachman** [comment]
Changed to BASH
