### ISSUE TITLE
Explain mor eclearly in help how to select country, and report country name

### ISSUE THREAD

**Issue by jpellegrini** [garrylachman/covid19-cli#7]
Hello!

It would be nice to explain, in the help text, how the user should enter the country (two-letter abbreviation? full name? how would I know exactly how to enter some country?)

Also, it would be nice, perhaps, to report the full country name in the output:

```
./covid19-cli.sh -c aa
...
 ✔  Country: aa
Cases: 1, Deaths: 0, Recovered: 0
```
Hm, but what is the user is not sure if `aa` is really the country she wanted to select?

**Comment by garrylachman** [comment]
```
./covid19-cli.sh -l
```

You will see the full countries list, use full name like in the list
